// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80TWPrQgZM-RVkBgh5YAUlebSti2hx1o',
    appId: '1:116756249723:web:bc29fa50c1cf31895836de',
    messagingSenderId: '116756249723',
    projectId: 'test1-9c7f5',
    authDomain: 'test1-9c7f5.firebaseapp.com',
    storageBucket: 'test1-9c7f5.firebasestorage.app',
    measurementId: 'G-T58GHJP1LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ip9Bau3dTZ7LYNRROaT3rKToZlM9U6Q',
    appId: '1:116756249723:android:bc34249273424ed45836de',
    messagingSenderId: '116756249723',
    projectId: 'test1-9c7f5',
    storageBucket: 'test1-9c7f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBT82E1K4gppkKWF8S3P5hoAYAT23dg_k',
    appId: '1:116756249723:ios:adb2b91b466467f65836de',
    messagingSenderId: '116756249723',
    projectId: 'test1-9c7f5',
    storageBucket: 'test1-9c7f5.firebasestorage.app',
    iosBundleId: 'com.example.apptest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBT82E1K4gppkKWF8S3P5hoAYAT23dg_k',
    appId: '1:116756249723:ios:adb2b91b466467f65836de',
    messagingSenderId: '116756249723',
    projectId: 'test1-9c7f5',
    storageBucket: 'test1-9c7f5.firebasestorage.app',
    iosBundleId: 'com.example.apptest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA80TWPrQgZM-RVkBgh5YAUlebSti2hx1o',
    appId: '1:116756249723:web:c71f6264fddf1c555836de',
    messagingSenderId: '116756249723',
    projectId: 'test1-9c7f5',
    authDomain: 'test1-9c7f5.firebaseapp.com',
    storageBucket: 'test1-9c7f5.firebasestorage.app',
    measurementId: 'G-H8GFY1Z2D7',
  );
}
